"use strict";
const $=id=>document.getElementById(id),calendar=$("calendar"),monthEl=$("month"),type=$("type"),rider=$("rider"),horse=$("horse"),raceName=$("raceName"),from=$("from"),to=$("to"),note=$("note"),raceBox=$("raceBox"),horseFilter=$("horseFilter"),workCount=$("workCount"),raceDaysCount=$("raceDaysCount");
const months=["Január","Február","Marec","Apríl","Máj","Jún","Júl","August","September","Október","November","December"];
let date=new Date(),selectedDate=null,editId=null,installPrompt=null,events=loadEvents();

function loadEvents(){try{return(JSON.parse(localStorage.getItem("events"))||[]).map(normalizeEvent)}catch{return[]}}
function save(){localStorage.setItem("events",JSON.stringify(events))}
function norm(v){return(v||"").trim().toLocaleLowerCase("sk")}
function parseDate(s){if(!s)return null;const[y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}
function dateKey(y,m,d){return`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`}
function uuid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function normalizeEvent(e){const d=parseDate(e.date);return{id:String(e.id||uuid()),type:e.type==="Trening"?"Tréning":e.type,rider:e.rider||"",horse:e.horse||"",note:e.note||"",date:d?dateKey(d.getFullYear(),d.getMonth(),d.getDate()):null,raceName:e.raceName||"",from:e.from||null,to:e.to||null}}

type.addEventListener("change",()=>raceBox.classList.toggle("hidden",type.value!=="Preteky"));
horseFilter.addEventListener("change",render);
$("weekdays").replaceChildren(...["Po","Ut","St","Št","Pi","So","Ne"].map(name=>{const el=document.createElement("div");el.className="weekday";el.textContent=name;return el}));

function loadHorses(){const selected=horseFilter.value,names=[...new Set(events.map(e=>e.horse).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"sk"));horseFilter.replaceChildren(new Option("všetky kone",""),...names.map(h=>new Option(h,h)));horseFilter.value=names.includes(selected)?selected:""}
function render(){calendar.replaceChildren();const y=date.getFullYear(),m=date.getMonth(),last=new Date(y,m+1,0),start=(new Date(y,m,1).getDay()+6)%7;monthEl.textContent=`${months[m]} ${y}`;for(let i=0;i<start;i++)calendar.append(document.createElement("div"));const filter=norm(horseFilter.value);for(let d=1;d<=last.getDate();d++){const key=dateKey(y,m,d),current=parseDate(key),cell=document.createElement("div");cell.className="day";cell.addEventListener("click",()=>openNew(key));const number=document.createElement("b");number.textContent=d;cell.append(number);events.filter(e=>(!filter||norm(e.horse)===filter)&&(e.type==="Preteky"?(parseDate(e.from)<=current&&parseDate(e.to)>=current):e.date===key)).forEach(e=>{const item=document.createElement("div");item.addEventListener("click",ev=>openEdit(ev,e.id));if(e.type==="Preteky"){item.className="race-bar "+(current.getTime()===parseDate(e.from)?.getTime()?"race-start":current.getTime()===parseDate(e.to)?.getTime()?"race-end":"race-mid");item.textContent=e.raceName||"Preteky"}else{item.className="training";item.textContent=`${e.horse||"?"} – ${e.type}`}cell.append(item)});calendar.append(cell)}updateStats();loadHorses()}
function openNew(key){selectedDate=key;editId=null;[rider,horse,note,raceName,from,to].forEach(el=>el.value="");type.value="Tréning";raceBox.classList.add("hidden");$("delete").style.display="none";$("modal").classList.remove("hidden")}
function openEdit(ev,id){ev.stopPropagation();const e=events.find(x=>x.id===id);if(!e)return;editId=id;selectedDate=e.date;type.value=e.type;rider.value=e.rider;horse.value=e.horse;note.value=e.note;if(e.type==="Preteky"){raceBox.classList.remove("hidden");raceName.value=e.raceName;from.value=e.from;to.value=e.to}else raceBox.classList.add("hidden");$("delete").style.display="block";$("modal").classList.remove("hidden")}
function updateStats(){const start=new Date(date.getFullYear(),date.getMonth(),1),end=new Date(date.getFullYear(),date.getMonth()+1,0),filter=norm(horseFilter.value),filtered=events.filter(e=>(!filter||norm(e.horse)===filter)&&(e.type==="Preteky"?(parseDate(e.to)>=start&&parseDate(e.from)<=end):(parseDate(e.date)>=start&&parseDate(e.date)<=end)));workCount.textContent=filtered.filter(e=>["Tréning","Jazdenie","Lonž"].includes(e.type)).length;raceDaysCount.textContent=filtered.filter(e=>e.type==="Preteky").reduce((sum,e)=>{const a=new Date(Math.max(parseDate(e.from),start)),b=new Date(Math.min(parseDate(e.to),end));return sum+Math.floor((b-a)/86400000)+1},0)}

$("save").onclick=()=>{const isRace=type.value==="Preteky";if(!horse.value.trim())return alert("Zadaj meno koňa.");if(isRace&&(!from.value||!to.value||from.value>to.value))return alert("Skontroluj dátumy pretekov.");const e={id:editId||uuid(),type:type.value,rider:rider.value.trim(),horse:horse.value.trim(),note:note.value.trim(),date:isRace?null:selectedDate,raceName:isRace?raceName.value.trim():"",from:isRace?from.value:null,to:isRace?to.value:null};const i=events.findIndex(x=>x.id===editId);if(i>=0)events[i]=e;else events.push(e);save();$("modal").classList.add("hidden");editId=null;render()};
$("delete").onclick=()=>{if(!editId)return;events=events.filter(e=>e.id!==editId);save();$("modal").classList.add("hidden");editId=null;render()};
$("close").onclick=()=>$("modal").classList.add("hidden");$("prev").onclick=()=>{date.setMonth(date.getMonth()-1);render()};$("next").onclick=()=>{date.setMonth(date.getMonth()+1);render()};

$("exportBackup").onclick=()=>{const payload=JSON.stringify({app:"jazdecky-kalendar",version:1,exportedAt:new Date().toISOString(),events},null,2),blob=new Blob([payload],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`jazdecky-kalendar-zaloha-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
$("importBackup").onclick=()=>$("backupFile").click();
$("backupFile").onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.app!=="jazdecky-kalendar"||!Array.isArray(data.events))throw new Error();if(!confirm(`Obnoviť ${data.events.length} záznamov? Súčasné údaje sa nahradia.`))return;events=data.events.map(normalizeEvent);save();render();alert("Záloha bola obnovená.")}catch{alert("Toto nie je platná záloha jazdeckého kalendára.")}finally{ev.target.value=""}};

let pdfFont=null;fetch("./Noto_Sans/static/NotoSans-Regular.ttf").then(r=>r.arrayBuffer()).then(buffer=>{let value="";new Uint8Array(buffer).forEach(byte=>value+=String.fromCharCode(byte));pdfFont=btoa(value)}).catch(()=>{});
$("pdfMonthHorse").onclick=()=>{if(!window.jspdf)return alert("PDF knižnica nie je dostupná.");const filter=norm(horseFilter.value);if(!filter)return alert("Vyber koňa!");const{jsPDF}=window.jspdf,doc=new jsPDF();if(pdfFont){doc.addFileToVFS("NotoSans.ttf",pdfFont);doc.addFont("NotoSans.ttf","NotoSans","normal");doc.setFont("NotoSans")}const y=date.getFullYear(),m=date.getMonth(),start=new Date(y,m,1),end=new Date(y,m+1,0),filtered=events.filter(e=>norm(e.horse)===filter&&(e.type==="Preteky"?(parseDate(e.to)>=start&&parseDate(e.from)<=end):(parseDate(e.date)>=start&&parseDate(e.date)<=end)));doc.setFontSize(14);doc.text(`${horseFilter.value} – ${months[m]} ${y}`,20,20);let pos=38;filtered.forEach(e=>{const line=e.type==="Preteky"?`${e.raceName||"Preteky"}: ${e.from} – ${e.to}`:`${e.date}: ${e.type}, ${e.rider}`;doc.splitTextToSize(line,170).forEach(part=>{if(pos>280){doc.addPage();pos=20}doc.text(part,20,pos);pos+=8})});doc.save(`${horseFilter.value}-${y}-${m+1}.pdf`)};

window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;$("installApp").classList.remove("hidden")});
$("installApp").onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("installApp").classList.add("hidden")};
window.addEventListener("appinstalled",()=>$("installApp").classList.add("hidden"));
if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.error));
save();render();
